chore: github eventでコンテキスト情報を取得するように変更

diff --git a/.github/workflows/check-dependencies.yml b/.github/workflows/check-dependencies.yml
--- a/.github/workflows/check-dependencies.yml
+++ b/.github/workflows/check-dependencies.yml
@@ -17,22 +17,24 @@ jobs:
       - name: Setup Application Runtime
         uses: ./.github/actions/setup-application-runtime
 
-      - name: Get current branch
-        id: branch
-        run: |
-          branch=$(git branch --show-current)
+      # - name: Get current branch
+      #   id: branch
+      #   run: |
+      #     branch=$(git branch --show-current)
 
-          if [ -z "$branch" ]; then
-            echo "Failed to get branch"
-            exit 1
-          fi
+      #     if [ -z "$branch" ]; then
+      #       echo "Failed to get branch"
+      #       exit 1
+      #     fi
 
-          echo "branch=$branch" >> $GITHUB_OUTPUT
+      #     echo "branch=$branch" >> $GITHUB_OUTPUT
 
       - name: Check package dependencies
         id: dependencies
         run: |
-          baseRefName=$(gh pr view ${{ steps.branch.outputs.branch }} --json baseRefName --jq .baseRefName)
+          # baseRefName=$(gh pr view ${{ steps.branch.outputs.branch }} --json baseRefName --jq .baseRefName)
+
+          baseRefName=${{ github.base_ref }}
 
           echo "The base branch is $baseRefName"
 
@@ -47,26 +49,26 @@ jobs:
             echo "$diff" > $path
             echo "path=$path" >> $GITHUB_OUTPUT
           fi
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        # env:
+        #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Get PR number
-        id: number
-        if: $${{ steps.dependencies.outputs.path != '' }}
-        run: |
-          number=$(gh pr list --head $${{ steps.branch.outputs.branch != '' }}  --state open --json number --jq '.[0].number')
+      # - name: Get PR number
+      #   id: number
+      #   if: $${{ steps.dependencies.outputs.path != '' }}
+      #   run: |
+      #     number=$(gh pr list --head $${{ steps.branch.outputs.branch != '' }}  --state open --json number --jq '.[0].number')
 
-          if [ -z "$number" ]; then
-            echo "Failed to get PR number"
-            exit 1
-          fi
+      #     if [ -z "$number" ]; then
+      #       echo "Failed to get PR number"
+      #       exit 1
+      #     fi
 
-          echo "number=$number" >> $GITHUB_OUTPUT
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #     echo "number=$number" >> $GITHUB_OUTPUT
+      #   env:
+      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Comment
-        if: ${{ steps.number.outputs.number != '' }}
-        run: gh pr comment "${{ steps.number.outputs.number }}" --body-file "${{ steps.dependencies.outputs.path }}"
+        if: $${{ steps.dependencies.outputs.path != '' }}
+        run: gh pr comment "${{ github.event.pull_request.number }}" --body-file "${{ steps.dependencies.outputs.path }}"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
